In [1]:
import pandas as pd
import numpy as np

In [2]:
import sys
print(sys.executable)

/home/ishido/Desktop/Aj/New proj/HELP extend/environment/venv/bin/python

In [3]:
PPI_edges = pd.read_csv('../../../data/lung/lung_PPI_final.csv')

In [4]:
labels = pd.read_csv('../../../data/lung/Crispr_labels_final.csv')

In [5]:
expressions = pd.read_csv('../../../data/lung/Lung_expression_final.csv')

In [6]:
mutations = pd.read_csv('../../../data/lung/mutations_final.csv')

In [7]:
common = set(expressions['ModelID']) & set(labels['ModelID'])
len(common)

123

In [8]:
len(common & set(mutations['ModelID']))

123

In [9]:
expressions = expressions[expressions['ModelID'].isin(common)]
mutations = mutations[mutations['ModelID'].isin(common)]
labels = labels[labels['ModelID'].isin(common)]

In [10]:
expressions.shape

(123, 18343)

In [11]:
mutations.shape

(123, 17137)

In [12]:
labels.shape

(123, 17850)

In [13]:
expressions.to_csv("../../../data/lung/final/expressions.csv",index=False)

KeyboardInterrupt:

In [ ]:
mutations.to_csv("../../../data/lung/final/mutations.csv",index=False)

In [ ]:
labels.to_csv("../../../data/lung/final/labels.csv",index = False)

In [13]:
exprxn = pd.read_csv("../../../data/lung/Lung_expression_final.csv")

In [14]:
exprxn

,ModelID,TSPAN6,TNMD,DPM1,SCYL3,FIRRM,FGR,CFH,FUCA2,GCLC,...,CCDC39,UPK3BL2,ARHGAP11B,ASDURF,DERPC,NOTCH2NLC,H3C2,NPBWR1,ACTL10,PRRC2B
0,ACH-001113,4.956577,0.000000,7.577648,3.179411,4.765742,0.037483,1.510547,3.103039,6.697482,...,2.724965,5.915177,1.577944,4.334225,4.395214,3.427618,2.763120,0.414727,0.077634,5.134808
1,ACH-000327,3.759710,0.000000,6.062055,1.931978,2.801039,0.008343,3.155547,6.022998,3.989239,...,0.332504,2.598687,1.495506,0.769006,1.228295,4.941379,1.014255,0.167291,0.984557,3.744742
2,ACH-000705,4.643816,0.000000,6.477998,2.449667,4.400859,0.038055,0.225467,2.721062,6.441122,...,2.128208,4.165631,2.328463,1.084248,3.312272,2.231429,1.444450,0.042438,0.259432,5.131668
3,ACH-000528,4.764797,0.000000,7.203309,3.102794,4.878814,0.015458,1.114007,6.858242,4.421156,...,1.389137,3.436023,2.576604,1.972560,2.300543,2.660360,1.135298,0.033873,0.096988,6.522283
4,ACH-002075,2.575724,0.000000,6.881897,2.784994,4.405652,0.824182,0.315560,3.281350,4.785237,...,2.331659,2.802551,1.395227,2.693288,4.189445,1.039735,1.867983,0.053257,1.616377,5.739565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,ACH-000666,3.786199,0.000000,5.651422,2.292849,3.870641,0.058922,7.067908,7.460841,6.209605,...,1.531359,3.134515,1.538404,0.984479,2.400278,2.485156,1.571769,0.037408,0.060065,6.601544
208,ACH-000872,5.066873,0.000000,6.599395,3.109707,3.877617,0.014222,6.936249,6.212412,4.613761,...,1.611574,3.850129,2.693630,2.035997,2.609623,2.330105,1.244351,0.000000,1.190368,5.063589
209,ACH-000121,4.332199,0.113282,6.804634,2.363227,3.489569,0.065727,2.724546,6.092596,6.539840,...,2.780041,3.593760,3.351240,1.776517,3.791022,3.806097,1.743618,0.338120,0.784378,5.394603
210,ACH-000781,3.718822,0.000000,5.960069,2.118742,4.046299,0.000000,6.423397,6.678016,7.790290,...,1.613070,2.611656,1.990813,1.638129,2.520191,3.061909,0.741003,0.005669,0.099357,5.705663
211,ACH-000830,3.610157,0.000000,6.466598,2.776647,4.780798,0.362481,0.148231,0.922038,4.035184,...,2.992649,3.851789,3.257708,1.887416,4.049613,0.109373,1.660399,0.000000,1.792231,7.289263

In [15]:
ppi = pd.read_csv("../../../data/lung/lung_PPI_final.csv")
ppi

              A        B  combined_score
0        MAP2K4     FLNC               2
1          FNTA    ACVR1               2
2         GATA2      PML               2
3          RPA2    STAT3               2
4          ARF1     GGA3               2
...         ...      ...             ...
1527575   LAMA2    FBLN2               2
1527576    BMP1     DSPP               1
1527577   SNAI1    LOXL1               2
1527578   FBLN1  COL18A1               2
1527579   FBLN1    LAMA2               2

[1527580 rows x 3 columns]

In [16]:
exprxn_values = exprxn.drop('ModelID',axis=1)

In [17]:
exprxn_values

,TSPAN6,TNMD,DPM1,SCYL3,FIRRM,FGR,CFH,FUCA2,GCLC,NFYA,...,CCDC39,UPK3BL2,ARHGAP11B,ASDURF,DERPC,NOTCH2NLC,H3C2,NPBWR1,ACTL10,PRRC2B
0,4.956577,0.000000,7.577648,3.179411,4.765742,0.037483,1.510547,3.103039,6.697482,4.852304,...,2.724965,5.915177,1.577944,4.334225,4.395214,3.427618,2.763120,0.414727,0.077634,5.134808
1,3.759710,0.000000,6.062055,1.931978,2.801039,0.008343,3.155547,6.022998,3.989239,2.674431,...,0.332504,2.598687,1.495506,0.769006,1.228295,4.941379,1.014255,0.167291,0.984557,3.744742
2,4.643816,0.000000,6.477998,2.449667,4.400859,0.038055,0.225467,2.721062,6.441122,4.496175,...,2.128208,4.165631,2.328463,1.084248,3.312272,2.231429,1.444450,0.042438,0.259432,5.131668
3,4.764797,0.000000,7.203309,3.102794,4.878814,0.015458,1.114007,6.858242,4.421156,4.272075,...,1.389137,3.436023,2.576604,1.972560,2.300543,2.660360,1.135298,0.033873,0.096988,6.522283
4,2.575724,0.000000,6.881897,2.784994,4.405652,0.824182,0.315560,3.281350,4.785237,4.929000,...,2.331659,2.802551,1.395227,2.693288,4.189445,1.039735,1.867983,0.053257,1.616377,5.739565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,3.786199,0.000000,5.651422,2.292849,3.870641,0.058922,7.067908,7.460841,6.209605,4.207651,...,1.531359,3.134515,1.538404,0.984479,2.400278,2.485156,1.571769,0.037408,0.060065,6.601544
208,5.066873,0.000000,6.599395,3.109707,3.877617,0.014222,6.936249,6.212412,4.613761,3.582496,...,1.611574,3.850129,2.693630,2.035997,2.609623,2.330105,1.244351,0.000000,1.190368,5.063589
209,4.332199,0.113282,6.804634,2.363227,3.489569,0.065727,2.724546,6.092596,6.539840,4.211316,...,2.780041,3.593760,3.351240,1.776517,3.791022,3.806097,1.743618,0.338120,0.784378,5.394603
210,3.718822,0.000000,5.960069,2.118742,4.046299,0.000000,6.423397,6.678016,7.790290,3.551331,...,1.613070,2.611656,1.990813,1.638129,2.520191,3.061909,0.741003,0.005669,0.099357,5.705663
211,3.610157,0.000000,6.466598,2.776647,4.780798,0.362481,0.148231,0.922038,4.035184,5.539438,...,2.992649,3.851789,3.257708,1.887416,4.049613,0.109373,1.660399,0.000000,1.792231,7.289263

In [18]:
A_values = exprxn_values[ppi['A']].values
B_values = exprxn_values[ppi['B']].values

In [ ]:
A_Centered = A_values - A_values.mean(axis=0)
B_Centered = B_values - B_values.mean(axis=0)

In [ ]:
num = (A_Centered * B_Centered).sum(axis=0)

In [ ]:
denom = np.sqrt((A_Centered**2).sum(axis=0) * (B_Centered**2).sum(axis=0))

In [ ]:
coexpression = num / denom
coexpression[10:]

In [ ]:
np.isnan(coexpression).sum()

In [ ]:
coexpression = np.nan_to_num(coexpression, nan=0.0)

In [ ]:
coexpression.shape

In [ ]:
np.isnan(coexpression).sum()

In [ ]:
ppi['coexpression'] = coexpression
ppi.head()

In [ ]:
ppi.to_csv('../../../data/lung/final/lung_PPI_final.csv', index=False)