In [1]:
import pandas as pd
import numpy as np

In [5]:
first_chunk = True

for chunk in pd.read_csv("../../../data/raw/PPIs/human_annotated_PPIs.txt", sep="\t",chunksize=50000, usecols=["symbol1", "symbol2", "lung"]):
    colomns_to_keep = chunk[['symbol1','symbol2','lung']]
    
    filtered = colomns_to_keep[colomns_to_keep['lung'] >= 1]
    
    if first_chunk:
        filtered.to_csv('../../../data/lung/lung_filter.csv', index=False, mode='w', header=True)
        first_chunk = False
    else:
        filtered.to_csv('../../../data/lung/lung_filter.csv', index=False, mode='a', header=False)

In [2]:
lung_filter = pd.read_csv('../../../data/lung/lung_filter.csv')
lung_filter.rename(columns={'symbol1':'A','symbol2':'B','kidney':'Combined_score'})

              A        B  lung
0        MAP2K4     FLNC     2
1          FNTA    ACVR1     2
2         GATA2      PML     2
3          RPA2    STAT3     2
4          ARF1     GGA3     2
...         ...      ...   ...
1559929   LAMA2    FBLN2     2
1559930    BMP1     DSPP     1
1559931   SNAI1    LOXL1     2
1559932   FBLN1  COL18A1     2
1559933   FBLN1    LAMA2     2

[1559934 rows x 3 columns]

In [3]:
lung_filter.isnull().any()

symbol1    False
symbol2    False
lung       False
dtype: bool

In [4]:
lung_filter[lung_filter['symbol1'] == lung_filter['symbol2']].sum()

symbol1    MCM2CSRP1KMT2APKD2LMO2RPLP2SNRPACLUFASNS100PSY...
symbol2    MCM2CSRP1KMT2APKD2LMO2RPLP2SNRPACLUFASNS100PSY...
lung                                                   11043
dtype: object

In [5]:
lung_filter = lung_filter[lung_filter['symbol1'] != lung_filter['symbol2']]

In [6]:
lung_filter.shape

(1554404, 3)

In [7]:
lung_filter.duplicated().sum()

np.int64(1074)

In [8]:
lung_filter = lung_filter.drop_duplicates()

In [9]:
lung_filter.shape

(1553330, 3)

In [10]:
pair = lung_filter[['symbol1','symbol2']]
print (pair)

        symbol1  symbol2
0        MAP2K4     FLNC
1          FNTA    ACVR1
2         GATA2      PML
3          RPA2    STAT3
4          ARF1     GGA3
...         ...      ...
1559929   LAMA2    FBLN2
1559930    BMP1     DSPP
1559931   SNAI1    LOXL1
1559932   FBLN1  COL18A1
1559933   FBLN1    LAMA2

[1553330 rows x 2 columns]

In [11]:
pair_filtered = pair.loc[pd.DataFrame(np.sort(pair.values, axis=1), index=pair.index).drop_duplicates().index]
print(pair_filtered)

        symbol1  symbol2
0        MAP2K4     FLNC
1          FNTA    ACVR1
2         GATA2      PML
3          RPA2    STAT3
4          ARF1     GGA3
...         ...      ...
1559929   LAMA2    FBLN2
1559930    BMP1     DSPP
1559931   SNAI1    LOXL1
1559932   FBLN1  COL18A1
1559933   FBLN1    LAMA2

[1548048 rows x 2 columns]

In [12]:
lung_filter = lung_filter.loc[pair_filtered.index]

In [13]:
lung_filter.shape

(1548048, 3)

In [14]:
expressions= pd.read_csv('../../../data/raw/depmap/OmicsExpressionTPMLogp1HumanProteinCodingGenes.csv', nrows=0)

In [15]:
expressions

Empty DataFrame
Columns: [Unnamed: 0, SequencingID, ModelID, IsDefaultEntryForModel, ModelConditionID, IsDefaultEntryForMC, TSPAN6 (7105), TNMD (64102), DPM1 (8813), SCYL3 (57147), FIRRM (55732), FGR (2268), CFH (3075), FUCA2 (2519), GCLC (2729), NFYA (4800), STPG1 (90529), NIPAL3 (57185), LAS1L (81887), ENPP4 (22875), SEMA3F (6405), CFTR (1080), ANKIB1 (54467), CYP51A1 (1595), KRIT1 (889), RAD52 (5893), MYH16 (84176), BAD (572), LAP3 (51056), CD99 (4267), HS3ST1 (9957), AOC1 (26), WNT16 (51384), HECW1 (23072), MAD1L1 (8379), LASP1 (3927), SNX11 (29916), TMEM176A (55365), M6PR (4074), KLHL13 (90293), CYP26B1 (56603), ICA1 (3382), DBNDD1 (79007), ALS2 (57679), CASP10 (843), CFLAR (8837), TFPI (7035), NDUFAF7 (55471), RBM5 (10181), MTMR7 (9108), SLC7A2 (6542), ARF5 (381), SARM1 (23098), POLDIP2 (26073), PLXND1 (23129), AK2 (204), CD38 (952), FKBP4 (2288), KDM1A (23028), RBM6 (10180), CAMKK1 (84254), RECQL (5965), VPS50 (55610), HSPB6 (126393), ARHGAP33 (115703), NDUFAB1 (4706), PDK4 (5166), SLC22A16 (85413), ZMYND10 (51364), ABCB5 (340273), ARX (170302), SLC25A13 (10165), ST7 (7982), CDC27 (996), SLC4A1 (6521), CALCR (799), HCCS (3052), DVL2 (1856), PRSS22 (64063), UPF1 (5976), SKAP2 (8935), SLC25A5 (292), MCUB (55013), HOXA11 (3207), POLR2J (5439), DHX33 (56919), MEOX1 (4222), THSD7A (221981), LIG3 (3980), RPAP3 (79657), ACSM3 (6296), REXO5 (81691), CIAPIN1 (57019), SPPL2B (56928), ATOSB (80256), COPZ2 (51226), PRKAR2B (5577), MSL3 (10943), CREBBP (1387), TSPOAP1 (9256), ...]
Index: []

[0 rows x 19221 columns]

In [16]:
gene_cols = expressions.columns[6:]   
gene_cols

Index(['TSPAN6 (7105)', 'TNMD (64102)', 'DPM1 (8813)', 'SCYL3 (57147)',
       'FIRRM (55732)', 'FGR (2268)', 'CFH (3075)', 'FUCA2 (2519)',
       'GCLC (2729)', 'NFYA (4800)',
       ...
       'ATXN8 (724066)', 'SMIM42 (117981789)', 'NPBWR1 (2831)',
       'ACTL10 (170487)', 'RNF228 (122319436)', 'PANO1 (101927423)',
       'HRURF (120766137)', 'PRRC2B (84726)', 'F8A2 (474383)', 'F8A1 (8263)'],
      dtype='str', length=19215)

In [17]:
exprn_genes = expressions.columns[6:].str.split(" (",regex=False).str[0]

In [18]:
(~lung_filter["symbol1"].isin(exprn_genes)).sum()

np.int64(10441)

In [19]:
lung_filter[~lung_filter["symbol1"].isin(exprn_genes)]["symbol1"].nunique()

1051

In [20]:
(~lung_filter["symbol2"].isin(exprn_genes)).sum()

np.int64(10355)

In [21]:
lung_filter[~lung_filter["symbol2"].isin(exprn_genes)]["symbol2"].nunique()

736

In [22]:
lung_expr_filtered = lung_filter[lung_filter["symbol1"].isin(exprn_genes) & lung_filter["symbol2"].isin(exprn_genes)]

lung_expr_filtered.shape

(1527580, 3)

In [23]:
pd.concat([lung_expr_filtered["symbol1"], lung_expr_filtered["symbol2"]]).nunique()

18342

In [24]:
gene = pd.read_csv('../../../data/raw/depmap/CRISPRGeneEffect.csv',nrows=0)

In [25]:
gene_lab = gene.columns[1:].str.split(" (",regex=False).str[0]
gene_lab

Index(['A1BG', 'A1CF', 'A2M', 'A2ML1', 'A3GALT2', 'A4GALT', 'A4GNT', 'AAAS',
       'AACS', 'AADAC',
       ...
       'ZWILCH', 'ZWINT', 'ZXDA', 'ZXDB', 'ZXDC', 'ZYG11A', 'ZYG11B', 'ZYX',
       'ZZEF1', 'ZZZ3'],
      dtype='str', length=18435)

In [26]:
ppi_genes = pd.concat([lung_expr_filtered["symbol1"], lung_expr_filtered["symbol2"]]).unique()

sum(pd.Series(ppi_genes).isin(gene_lab))

17849

In [27]:
lung_expr_filtered.rename(columns={'symbol1':'A','symbol2':'B','lung':'combined_score'})

              A        B  combined_score
0        MAP2K4     FLNC               2
1          FNTA    ACVR1               2
2         GATA2      PML               2
3          RPA2    STAT3               2
4          ARF1     GGA3               2
...         ...      ...             ...
1559929   LAMA2    FBLN2               2
1559930    BMP1     DSPP               1
1559931   SNAI1    LOXL1               2
1559932   FBLN1  COL18A1               2
1559933   FBLN1    LAMA2               2

[1527580 rows x 3 columns]

In [28]:
for i in range(0,len(lung_expr_filtered),100000):
    chunk = lung_expr_filtered.iloc[i:i+100000]
    if i == 0:
        chunk.to_csv('../../../data/lung/lung_PPI_final.csv',index=False,mode='w')
    else:
        chunk.to_csv('../../../data/lung/lung_PPI_final.csv',index=False,mode='a',header=False)

In [30]:
PPI_lung = pd.read_csv('../../../data/lung/lung_PPI_final.csv')

PPI_lung.rename(columns={'symbol1':'A','symbol2':'B','lung':'combined_score'}).to_csv('../../../data/lung/lung_PPI_final.csv', index=False)