In [1]:
import pandas as pd 
import numpy as np

In [1]:
import sys
print(sys.executable)

/home/ishido/Desktop/Aj/New proj/HELP extend/environment/venv/bin/python

In [2]:
PPI_edges = pd.read_csv('../data/processed/kidney_PPI_final.csv')

In [3]:
labels = pd.read_csv('../data/processed/Crispr_labels_final.csv')

In [4]:
expressions = pd.read_csv('../data/processed/Kidney_expression_final.csv')

In [5]:
mutations = pd.read_csv('../data/processed/Kidney_mutations_final.csv')

In [6]:
common = set(expressions['ModelID']) & set(labels['ModelID'])
len(common)

32

In [7]:
len(common & set(mutations['ModelID']))

32

In [8]:
expressions = expressions[expressions['ModelID'].isin(common)]
mutations = mutations[mutations['ModelID'].isin(common)]
labels = labels[labels['ModelID'].isin(common)]

In [9]:
expressions.shape

(32, 18360)

In [10]:
mutations.shape

(32, 17150)

In [11]:
labels.shape

(32, 17864)

In [13]:
expressions.to_csv("../data/Final/expressions.csv",index=False)

In [14]:
mutations.to_csv("../data/Final/mutations.csv",index=False)

In [15]:
labels.to_csv("../data/Final/labels.csv",index = False)

In [14]:
exprxn = pd.read_csv("../data/processed/Kidney_expression_final.csv")

In [ ]:
exprxn

,ModelID,TSPAN6,TNMD,DPM1,SCYL3,FIRRM,FGR,CFH,FUCA2,GCLC,...,CCDC39,UPK3BL2,ARHGAP11B,ASDURF,DERPC,NOTCH2NLC,H3C2,NPBWR1,ACTL10,PRRC2B
0,ACH-002438,4.336705,0.000000,6.879387,2.262824,3.256491,0.000000,2.253926,6.895436,3.470992,...,0.456676,1.819562,1.553459,2.227735,4.147062,3.458790,0.255362,0.024008,0.984538,4.949465
1,ACH-000792,3.500318,0.000000,6.572009,1.812749,3.596935,0.093977,0.508347,6.694044,4.797376,...,2.089447,1.716346,3.057705,0.701833,2.096609,4.620088,0.659900,0.271451,0.393398,5.311536
2,ACH-000317,3.551270,0.000000,6.121229,2.008612,2.559269,0.079367,4.279278,5.128755,2.962580,...,2.262349,3.567679,2.142609,0.966736,4.076764,3.735825,0.193359,0.179049,1.816018,5.852713
3,ACH-000313,3.815002,0.000000,5.790728,2.040068,2.488430,0.214781,6.010695,5.732893,4.818355,...,2.574240,3.410553,2.816823,1.277265,3.605435,4.499100,0.512084,0.085998,1.043813,6.262553
4,ACH-001398,4.363234,0.000000,7.044121,1.939708,3.001002,0.000000,5.802126,6.052003,4.781118,...,0.553027,3.737059,1.613800,2.627845,3.619706,4.617275,0.563187,0.495400,1.353459,4.534995
5,ACH-001200,2.745519,0.000000,5.975256,2.504030,4.151461,0.000000,1.761885,6.981065,3.944868,...,0.788148,4.487776,2.436034,3.444336,2.297133,3.649466,0.336071,0.000000,0.246098,6.068778
6,ACH-001688,4.304204,0.000000,4.627689,2.064835,2.407018,0.006383,1.377835,4.547573,2.267518,...,0.162523,5.947512,1.446981,0.126736,3.240294,3.480007,0.507673,0.154114,1.592536,3.702148
7,ACH-000428,3.718690,0.000000,6.672397,1.969410,3.263720,0.080280,1.697133,6.718595,4.281602,...,1.354746,2.313019,1.972579,2.292063,4.185367,2.900196,0.946023,1.069998,0.859691,5.345623
8,ACH-000684,2.841025,0.000000,6.861521,2.007027,4.000171,0.010151,4.765726,7.312003,3.254236,...,0.689704,2.508353,1.381533,0.993621,3.410581,4.150227,0.341549,0.180875,1.258151,2.091297
9,ACH-000429,3.656382,0.000000,6.082187,2.089559,2.811607,0.084331,4.963067,4.424459,3.808920,...,1.372239,3.478972,3.165299,2.005874,2.159413,2.163183,0.761976,0.099411,0.272465,3.332303
10,ACH-000234,3.573496,0.000000,6.459963,3.878735,3.498698,0.028146,1.144366,6.438559,7.185847,...,1.868742,3.580170,1.782081,0.847151,3.167504,3.210007,0.680033,0.095789,1.559981,5.937196
11,ACH-003451,5.740202,0.612758,6.006758,3.059833,3.384908,0.032588,7.703869,5.936923,5.704828,...,1.538181,1.218019,1.623623,2.372401,3.168456,3.108257,1.304201,0.017147,0.184716,5.774816
12,ACH-000600,3.940082,0.000000,6.602714,2.587994,3.950730,0.000000,6.132813,7.363679,3.885047,...,2.045013,2.907769,1.699565,2.167984,3.247865,2.979310,0.420340,0.391224,0.741829,5.649989
13,ACH-002533,5.283537,0.000000,7.109172,2.449804,4.080607,0.000000,4.151883,6.398484,4.508853,...,0.530201,1.350237,1.208586,3.286838,5.074921,5.036424,0.122518,0.540175,0.000000,4.674314
14,ACH-000459,3.111916,0.000000,6.125604,2.899203,4.238626,0.067855,5.027680,6.518578,6.052394,...,1.117462,3.007147,2.732345,1.827433,3.518107,4.219974,0.356978,0.108326,1.206381,5.993985
15,ACH-000262,4.099893,0.000000,7.208420,2.018349,3.991916,0.000000,4.417961,6.455474,4.413222,...,1.881845,2.839024,2.503565,1.924370,2.093969,1.939640,0.306006,0.060658,0.706851,5.573644
16,ACH-001310,5.110793,0.000000,6.551741,2.372139,4.503603,0.091392,4.388403,6.361021,4.132017,...,2.310666,1.742088,2.527028,2.552982,4.933115,3.764006,0.734168,0.160474,0.554409,6.005948
17,ACH-000484,2.669315,0.000000,6.542546,2.409611,2.101754,0.212635,4.503387,5.244442,6.101007,...,1.918562,3.391722,3.645517,1.714540,3.686601,2.803215,1.239618,0.014625,1.947861,5.790960
18,ACH-000300,4.240734,0.000000,6.403321,2.749442,4.744344,0.035624,6.068116,6.467275,5.511436,...,1.364892,2.850993,2.851735,2.162065,3.385080,1.622092,1.134490,0.006404,0.933657,5.257708
19,ACH-000250,2.434946,0.000000,6.342743,2.670251,4.221382,0.188000,5.635487,6.935106,6.315050,...,1.571619,4.002847,2.876468,1.331562,3.287178,4.544399,0.664588,0.238360,1.049477,6.111812
20,ACH-001163,4.567831,0.717109,6.568405,2.108548,3.493045,0.000000,0.062590,4.931371,6.718019,...,0.525920,1.579861,2.416643,2.761636,3.264889,3.442847,1.926595,0.000000,0.052370,5.019751
21,ACH-002937,4.049474,0.000000,5.468169,1.715849,1.721871,0.000000,3.992007,5.012528,3.579011,...,0.141354,2.646695,0.850543,0.315075,2.948173,3.211263,0.187792,2.156982,0.787462,4.204720
22,ACH-000049,4.541372,0.000000,6.585768,2.313510,4.241695,0.036737,3.203485,6.644218,4.008012,...,1.489697,3.189926,2.962862,1.939813,3.120430,1.617186,1.385293,0.137837,0.379306,5.378630
23,ACH-000375,3.066017,0.022658,6.134213,2.556581,3.345856,0.000000,0.691986,3.806695,3.430285,...,1.529066,2.116661,3.054258,2.605814,3.284536,2.591727,1.418266,0.000000,0.198399,6.039105
24,ACH-001194,3.834003,0.000000,7.154575,2.629303,4.204704,0.047498,8.141841,6.075411,6.136677,...,1.644429,3.838619,3.621466,3.846323,3.753123,2.267796,0.354749,0.094541,0.327809,4.047163
25,ACH-000649,2.541101,0.000000,7.045421,2.138261,4.501223,0.000000,3.454355,6.997281,4.565597,...,1.218136,2.584573,3.275152,1.952009,4.400893,3.316573,0.748884,0.034909,0.700837,5.436328
26,ACH-000016,4.462530,0.000000,6.190176,2.318172,2.366722,0.000000,7.391630,6.127134,6.312458,...,1.625696,4.454794,1.676755,1.347989,3.788832,1.651646,0.936477,0.331444,1.168360,5.622740
27,ACH-000411,3.035960,0.000000,6.454929,2.434313,4.310231,0.000000,1.818912,6.588511,4.972454,...,1.714087,3.504455,2.160472,1.098325,4.082192,2.583801,0.532723,0.098670,0.701057,5.022159
28,ACH-000433,3.939010,0.000000,6.651957,2.487566,3.264751,0.000000,4.360554,6.050957,4.702525,...,1.366291,4.124568,1.527891,0.899019,4.858578,3.836116,1.007669,0.390630,0.412617,4.184883
29,ACH-002528,4.063839,0.000000,6.961091,2.288022,3.659205,0.000000,7.273460,6.552692,3.575772,...,0.249190,1.270152,1.215424,2.448497,4.343230,4.349401,0.384081,0.087563,0.782536,5.707061
30,ACH-000533,3.175275,0.000000,6.697190,2.802456,3.420612,0.014715,0.138218,0.956856,3.498213,...,1.715212,2.378828,2.947904,2.160943,3.087658,1.839327,1.085567,0.000000,0.097415,5.953587
31,ACH-000171,3.191177,0.000000,6.258807,2.713379,3.540337,0.038095,3.597412,6.505664,5.553812,...,2.009885,3.073637,2.655118,2.157008,4.164859,2.001881,1.316569,0.629548,0.295236,5.104639
32,ACH-002435,4.596518,0.059017,6.063820,1.926554,2.792683,0.000000,4.200599,5.926379,3.330600,...,0.179638,0.825724,1.129520,1.025213,3.980336,3.538166,0.852596,0.545848,0.328835,4.393094
33,ACH-000201,2.253672,0.000000,6.697774,3.615263,3.964814,0.041306,4.390282,6.809620,3.259505,...,1.563724,2.469042,2.771945,2.484187,3.929753,2.036982,2.588066,0.017309,0.331820,5.674156
34,ACH-000189,2.520319,0.000000,6.577403,1.751986,2.670777,0.045931,1.059909,5.391799,3.401710,...,2.276241,3.490557,2.608987,1.599975,3.367157,4.776062,0.279853,0.662276,1.381040,5.447354
35,ACH-000457,4.177009,0.000000,5.870838,2.320164,1.860438,0.000000,3.994715,6.174496,4.687296,...,1.225880,4.600609,1.884168,0.622730,3.785666,3.107457,0.115212,0.194370,1.239441,6.384782
36,ACH-000159,3.989230,0.000000,7.383523,2.045974,3.583050,0.084943,5.451969,5.891820,3.414689,...,2.197353,3.409031,3.723406,1.744419,3.724443,3.670602,0.635966,1.424175,1.528351,5.255063
37,ACH-000907,4.639684,0.000000,5.218677,1.917504,2.662178,0.000000,6.516077,6.600649,3.582580,...,1.195555,2.581088,2.187768,1.494907,2.490629,3.472020,0.371104,0.088182,0.585142,4.818283
38,ACH-001423,4.054640,0.000000,6.496641,1.321697,2.407293,0.000000,4.529396,5.287927,3.588649,...,1.282707,0.451544,1.519240,1.126471,3.833669,2.707810,0.000000,0.000000,0.657620,4.553834
39,ACH-000709,3.541515,0.000000,6.326893,1.817324,3.249456,0.030405,5.397334,6.330707,3.919102,...,0.901663,2.379712,1.690417,1.229822,3.035033,2.786299,0.283729,0.183704,0.818947,3.958472
40,ACH-001210,2.823582,0.142811,6.537590,2.401669,3.732801,0.000000,0.157224,7.071344,3.551799,...,1.137910,1.853081,3.200498,2.998573,3.451936,1.861118,0.973986,0.017613,0.056726,6.448695
41,ACH-003143,3.631745,0.000000,7.096272,2.439408,4.609134,0.124742,4.063555,6.553466,4.034154,...,1.670297,2.696321,2.941332,2.362128,4.941322,3.759912,1.320745,0.213080,0.701354,5.078994
42,ACH-000385,3.913531,0.000000,7.034348,2.532482,4.246172,0.025451,6.599856,6.808655,5.895988,...,1.174381,3.497114,2.048515,1.058926,2.991719,2.479709,0.453419,0.065157,1.472592,5.682874
43,ACH-000096,5.866584,0.139489,7.064139,3.675387,4.852289,0.000000,1.110129,5.796260,4.495088,...,1.521563,2.684704,2.837505,2.767600,4.716036,1.762340,1.286497,0.000000,0.171621,5.899860
44,ACH-000495,4.501102,0.000000,7.321270,2.167024,3.523537,0.103276,5.749711,6.161293,3.992750,...,2.361704,2.598322,1.546719,0.001082,3.921198,3.813627,0.000000,0.016871,1.728090,5.508140
45,ACH-000607,3.270397,0.000000,5.132334,3.061273,3.836914,0.056952,7.527946,5.372816,3.855003,...,1.861380,3.846082,2.649206,0.917535,3.543793,2.967836,1.970309,0.013987,0.169015,6.501856
46,ACH-000555,3.988130,0.000000,6.612981,2.182603,3.399166,0.012235,6.071098,6.075595,5.605322,...,0.980630,3.117128,1.576783,1.220937,3.123290,2.575087,0.542748,0.043874,0.683524,5.224986
47,ACH-001109,2.553267,0.000000,6.090392,2.534418,3.809219,0.000000,4.032551,6.588529,3.955341,...,2.227926,1.687625,2.736464,4.748896,3.709346,2.285518,1.461806,0.000000,1.729561,6.294615
48,ACH-000272,3.295575,0.000000,6.199957,1.554623,3.600781,0.000000,0.731281,6.911008,3.868242,...,0.582828,2.513392,2.262698,1.369567,3.071888,1.867723,0.245502,0.023956,1.010887,5.041970
49,ACH-000513,3.906919,0.000000,6.145351,2.023944,3.361970,0.048953,6.035745,4.242267,3.887545,...,1.253215,2.888463,0.907311,0.846078,2.131906,3.066950,0.173094,0.549701,0.318076,5.593939
50,ACH-001532,4.122051,0.000000,6.197915,1.996595,2.276565,0.022155,0.000000,5.879787,4.215321,...,1.227341,2.437095,2.210763,1.054876,4.278632,2.245271,0.532086,0.000000,0.042490,4.881082
51,ACH-001687,2.267383,0.000000,5.303817,1.154648,0.851320,0.014641,2.172036,4.969316,2.744084,...,0.095153,2.392246,0.451294,0.101833,2.162861,2.254047,0.000000,0.000000,0.080823,3.044840
52,ACH-000046,3.802038,0.000000,6.084245,2.155208,3.685794,0.015700,1.011288,6.905977,4.790511,...,1.272190,2.829787,1.893028,2.107611,4.134287,2.757646,1.333000,0.151959,0.519793,5.337586

In [15]:
ppi = pd.read_csv("../data/processed/kidney_PPI_final.csv")
ppi

              A        B  combined_score  coexpression
0        MAP2K4     FLNC               2      0.285217
1          FNTA    ACVR1               2      0.014917
2         GATA2      PML               2     -0.098040
3          RPA2    STAT3               2      0.350444
4          ARF1     GGA3               2      0.304046
...         ...      ...             ...           ...
1528071   LAMA2    FBLN2               1      0.301295
1528072    BMP1     DSPP               1     -0.197264
1528073   SNAI1    LOXL1               1      0.159567
1528074   FBLN1  COL18A1               2      0.070642
1528075   FBLN1    LAMA2               2      0.313868

[1528076 rows x 4 columns]

In [16]:
exprxn_values = exprxn.drop('ModelID',axis=1)

In [17]:
exprxn_values

,TSPAN6,TNMD,DPM1,SCYL3,FIRRM,FGR,CFH,FUCA2,GCLC,NFYA,...,CCDC39,UPK3BL2,ARHGAP11B,ASDURF,DERPC,NOTCH2NLC,H3C2,NPBWR1,ACTL10,PRRC2B
0,4.336705,0.000000,6.879387,2.262824,3.256491,0.000000,2.253926,6.895436,3.470992,4.308375,...,0.456676,1.819562,1.553459,2.227735,4.147062,3.458790,0.255362,0.024008,0.984538,4.949465
1,3.500318,0.000000,6.572009,1.812749,3.596935,0.093977,0.508347,6.694044,4.797376,7.350621,...,2.089447,1.716346,3.057705,0.701833,2.096609,4.620088,0.659900,0.271451,0.393398,5.311536
2,3.551270,0.000000,6.121229,2.008612,2.559269,0.079367,4.279278,5.128755,2.962580,2.837528,...,2.262349,3.567679,2.142609,0.966736,4.076764,3.735825,0.193359,0.179049,1.816018,5.852713
3,3.815002,0.000000,5.790728,2.040068,2.488430,0.214781,6.010695,5.732893,4.818355,3.799181,...,2.574240,3.410553,2.816823,1.277265,3.605435,4.499100,0.512084,0.085998,1.043813,6.262553
4,4.363234,0.000000,7.044121,1.939708,3.001002,0.000000,5.802126,6.052003,4.781118,3.327125,...,0.553027,3.737059,1.613800,2.627845,3.619706,4.617275,0.563187,0.495400,1.353459,4.534995
5,2.745519,0.000000,5.975256,2.504030,4.151461,0.000000,1.761885,6.981065,3.944868,3.833649,...,0.788148,4.487776,2.436034,3.444336,2.297133,3.649466,0.336071,0.000000,0.246098,6.068778
6,4.304204,0.000000,4.627689,2.064835,2.407018,0.006383,1.377835,4.547573,2.267518,2.670408,...,0.162523,5.947512,1.446981,0.126736,3.240294,3.480007,0.507673,0.154114,1.592536,3.702148
7,3.718690,0.000000,6.672397,1.969410,3.263720,0.080280,1.697133,6.718595,4.281602,3.401005,...,1.354746,2.313019,1.972579,2.292063,4.185367,2.900196,0.946023,1.069998,0.859691,5.345623
8,2.841025,0.000000,6.861521,2.007027,4.000171,0.010151,4.765726,7.312003,3.254236,3.313880,...,0.689704,2.508353,1.381533,0.993621,3.410581,4.150227,0.341549,0.180875,1.258151,2.091297
9,3.656382,0.000000,6.082187,2.089559,2.811607,0.084331,4.963067,4.424459,3.808920,2.636047,...,1.372239,3.478972,3.165299,2.005874,2.159413,2.163183,0.761976,0.099411,0.272465,3.332303
10,3.573496,0.000000,6.459963,3.878735,3.498698,0.028146,1.144366,6.438559,7.185847,4.298292,...,1.868742,3.580170,1.782081,0.847151,3.167504,3.210007,0.680033,0.095789,1.559981,5.937196
11,5.740202,0.612758,6.006758,3.059833,3.384908,0.032588,7.703869,5.936923,5.704828,5.451376,...,1.538181,1.218019,1.623623,2.372401,3.168456,3.108257,1.304201,0.017147,0.184716,5.774816
12,3.940082,0.000000,6.602714,2.587994,3.950730,0.000000,6.132813,7.363679,3.885047,4.064409,...,2.045013,2.907769,1.699565,2.167984,3.247865,2.979310,0.420340,0.391224,0.741829,5.649989
13,5.283537,0.000000,7.109172,2.449804,4.080607,0.000000,4.151883,6.398484,4.508853,3.578552,...,0.530201,1.350237,1.208586,3.286838,5.074921,5.036424,0.122518,0.540175,0.000000,4.674314
14,3.111916,0.000000,6.125604,2.899203,4.238626,0.067855,5.027680,6.518578,6.052394,3.964602,...,1.117462,3.007147,2.732345,1.827433,3.518107,4.219974,0.356978,0.108326,1.206381,5.993985
15,4.099893,0.000000,7.208420,2.018349,3.991916,0.000000,4.417961,6.455474,4.413222,4.014293,...,1.881845,2.839024,2.503565,1.924370,2.093969,1.939640,0.306006,0.060658,0.706851,5.573644
16,5.110793,0.000000,6.551741,2.372139,4.503603,0.091392,4.388403,6.361021,4.132017,3.894333,...,2.310666,1.742088,2.527028,2.552982,4.933115,3.764006,0.734168,0.160474,0.554409,6.005948
17,2.669315,0.000000,6.542546,2.409611,2.101754,0.212635,4.503387,5.244442,6.101007,4.676691,...,1.918562,3.391722,3.645517,1.714540,3.686601,2.803215,1.239618,0.014625,1.947861,5.790960
18,4.240734,0.000000,6.403321,2.749442,4.744344,0.035624,6.068116,6.467275,5.511436,3.471981,...,1.364892,2.850993,2.851735,2.162065,3.385080,1.622092,1.134490,0.006404,0.933657,5.257708
19,2.434946,0.000000,6.342743,2.670251,4.221382,0.188000,5.635487,6.935106,6.315050,4.298995,...,1.571619,4.002847,2.876468,1.331562,3.287178,4.544399,0.664588,0.238360,1.049477,6.111812
20,4.567831,0.717109,6.568405,2.108548,3.493045,0.000000,0.062590,4.931371,6.718019,3.283760,...,0.525920,1.579861,2.416643,2.761636,3.264889,3.442847,1.926595,0.000000,0.052370,5.019751
21,4.049474,0.000000,5.468169,1.715849,1.721871,0.000000,3.992007,5.012528,3.579011,2.677472,...,0.141354,2.646695,0.850543,0.315075,2.948173,3.211263,0.187792,2.156982,0.787462,4.204720
22,4.541372,0.000000,6.585768,2.313510,4.241695,0.036737,3.203485,6.644218,4.008012,4.334375,...,1.489697,3.189926,2.962862,1.939813,3.120430,1.617186,1.385293,0.137837,0.379306,5.378630
23,3.066017,0.022658,6.134213,2.556581,3.345856,0.000000,0.691986,3.806695,3.430285,4.471955,...,1.529066,2.116661,3.054258,2.605814,3.284536,2.591727,1.418266,0.000000,0.198399,6.039105
24,3.834003,0.000000,7.154575,2.629303,4.204704,0.047498,8.141841,6.075411,6.136677,3.675138,...,1.644429,3.838619,3.621466,3.846323,3.753123,2.267796,0.354749,0.094541,0.327809,4.047163
25,2.541101,0.000000,7.045421,2.138261,4.501223,0.000000,3.454355,6.997281,4.565597,3.781695,...,1.218136,2.584573,3.275152,1.952009,4.400893,3.316573,0.748884,0.034909,0.700837,5.436328
26,4.462530,0.000000,6.190176,2.318172,2.366722,0.000000,7.391630,6.127134,6.312458,3.797138,...,1.625696,4.454794,1.676755,1.347989,3.788832,1.651646,0.936477,0.331444,1.168360,5.622740
27,3.035960,0.000000,6.454929,2.434313,4.310231,0.000000,1.818912,6.588511,4.972454,3.877656,...,1.714087,3.504455,2.160472,1.098325,4.082192,2.583801,0.532723,0.098670,0.701057,5.022159
28,3.939010,0.000000,6.651957,2.487566,3.264751,0.000000,4.360554,6.050957,4.702525,2.791860,...,1.366291,4.124568,1.527891,0.899019,4.858578,3.836116,1.007669,0.390630,0.412617,4.184883
29,4.063839,0.000000,6.961091,2.288022,3.659205,0.000000,7.273460,6.552692,3.575772,3.924765,...,0.249190,1.270152,1.215424,2.448497,4.343230,4.349401,0.384081,0.087563,0.782536,5.707061
30,3.175275,0.000000,6.697190,2.802456,3.420612,0.014715,0.138218,0.956856,3.498213,3.754471,...,1.715212,2.378828,2.947904,2.160943,3.087658,1.839327,1.085567,0.000000,0.097415,5.953587
31,3.191177,0.000000,6.258807,2.713379,3.540337,0.038095,3.597412,6.505664,5.553812,4.196615,...,2.009885,3.073637,2.655118,2.157008,4.164859,2.001881,1.316569,0.629548,0.295236,5.104639
32,4.596518,0.059017,6.063820,1.926554,2.792683,0.000000,4.200599,5.926379,3.330600,3.740258,...,0.179638,0.825724,1.129520,1.025213,3.980336,3.538166,0.852596,0.545848,0.328835,4.393094
33,2.253672,0.000000,6.697774,3.615263,3.964814,0.041306,4.390282,6.809620,3.259505,4.214063,...,1.563724,2.469042,2.771945,2.484187,3.929753,2.036982,2.588066,0.017309,0.331820,5.674156
34,2.520319,0.000000,6.577403,1.751986,2.670777,0.045931,1.059909,5.391799,3.401710,3.387715,...,2.276241,3.490557,2.608987,1.599975,3.367157,4.776062,0.279853,0.662276,1.381040,5.447354
35,4.177009,0.000000,5.870838,2.320164,1.860438,0.000000,3.994715,6.174496,4.687296,3.824595,...,1.225880,4.600609,1.884168,0.622730,3.785666,3.107457,0.115212,0.194370,1.239441,6.384782
36,3.989230,0.000000,7.383523,2.045974,3.583050,0.084943,5.451969,5.891820,3.414689,3.354863,...,2.197353,3.409031,3.723406,1.744419,3.724443,3.670602,0.635966,1.424175,1.528351,5.255063
37,4.639684,0.000000,5.218677,1.917504,2.662178,0.000000,6.516077,6.600649,3.582580,3.342890,...,1.195555,2.581088,2.187768,1.494907,2.490629,3.472020,0.371104,0.088182,0.585142,4.818283
38,4.054640,0.000000,6.496641,1.321697,2.407293,0.000000,4.529396,5.287927,3.588649,3.433897,...,1.282707,0.451544,1.519240,1.126471,3.833669,2.707810,0.000000,0.000000,0.657620,4.553834
39,3.541515,0.000000,6.326893,1.817324,3.249456,0.030405,5.397334,6.330707,3.919102,3.450060,...,0.901663,2.379712,1.690417,1.229822,3.035033,2.786299,0.283729,0.183704,0.818947,3.958472
40,2.823582,0.142811,6.537590,2.401669,3.732801,0.000000,0.157224,7.071344,3.551799,5.434261,...,1.137910,1.853081,3.200498,2.998573,3.451936,1.861118,0.973986,0.017613,0.056726,6.448695
41,3.631745,0.000000,7.096272,2.439408,4.609134,0.124742,4.063555,6.553466,4.034154,4.300248,...,1.670297,2.696321,2.941332,2.362128,4.941322,3.759912,1.320745,0.213080,0.701354,5.078994
42,3.913531,0.000000,7.034348,2.532482,4.246172,0.025451,6.599856,6.808655,5.895988,3.692952,...,1.174381,3.497114,2.048515,1.058926,2.991719,2.479709,0.453419,0.065157,1.472592,5.682874
43,5.866584,0.139489,7.064139,3.675387,4.852289,0.000000,1.110129,5.796260,4.495088,4.725141,...,1.521563,2.684704,2.837505,2.767600,4.716036,1.762340,1.286497,0.000000,0.171621,5.899860
44,4.501102,0.000000,7.321270,2.167024,3.523537,0.103276,5.749711,6.161293,3.992750,3.577018,...,2.361704,2.598322,1.546719,0.001082,3.921198,3.813627,0.000000,0.016871,1.728090,5.508140
45,3.270397,0.000000,5.132334,3.061273,3.836914,0.056952,7.527946,5.372816,3.855003,4.254602,...,1.861380,3.846082,2.649206,0.917535,3.543793,2.967836,1.970309,0.013987,0.169015,6.501856
46,3.988130,0.000000,6.612981,2.182603,3.399166,0.012235,6.071098,6.075595,5.605322,2.980694,...,0.980630,3.117128,1.576783,1.220937,3.123290,2.575087,0.542748,0.043874,0.683524,5.224986
47,2.553267,0.000000,6.090392,2.534418,3.809219,0.000000,4.032551,6.588529,3.955341,4.765837,...,2.227926,1.687625,2.736464,4.748896,3.709346,2.285518,1.461806,0.000000,1.729561,6.294615
48,3.295575,0.000000,6.199957,1.554623,3.600781,0.000000,0.731281,6.911008,3.868242,3.063235,...,0.582828,2.513392,2.262698,1.369567,3.071888,1.867723,0.245502,0.023956,1.010887,5.041970
49,3.906919,0.000000,6.145351,2.023944,3.361970,0.048953,6.035745,4.242267,3.887545,3.527483,...,1.253215,2.888463,0.907311,0.846078,2.131906,3.066950,0.173094,0.549701,0.318076,5.593939
50,4.122051,0.000000,6.197915,1.996595,2.276565,0.022155,0.000000,5.879787,4.215321,4.097518,...,1.227341,2.437095,2.210763,1.054876,4.278632,2.245271,0.532086,0.000000,0.042490,4.881082
51,2.267383,0.000000,5.303817,1.154648,0.851320,0.014641,2.172036,4.969316,2.744084,2.564046,...,0.095153,2.392246,0.451294,0.101833,2.162861,2.254047,0.000000,0.000000,0.080823,3.044840
52,3.802038,0.000000,6.084245,2.155208,3.685794,0.015700,1.011288,6.905977,4.790511,3.188323,...,1.272190,2.829787,1.893028,2.107611,4.134287,2.757646,1.333000,0.151959,0.519793,5.337586

In [18]:
A_values = exprxn_values[ppi['A']].values
B_values = exprxn_values[ppi['B']].values

In [ ]:
A_values

array([[4.39719373, 6.08170179, 0.89110573, ..., 0.9523455 , 8.11163127,
        8.11163127],
       [3.61948344, 5.45035018, 3.5268826 , ..., 2.67617487, 0.64346742,
        0.64346742],
       [3.8047867 , 5.98831204, 0.48925313, ..., 1.18649422, 6.39804248,
        6.39804248],
       ...,
       [4.1561377 , 6.07386949, 0.01679724, ..., 1.25807263, 3.61963603,
        3.61963603],
       [2.84241572, 5.53107885, 0.16766236, ..., 0.69729165, 0.05463735,
        0.05463735],
       [4.39774821, 5.76531992, 0.12760291, ..., 0.75017856, 2.95254604,
        2.95254604]], shape=(53, 1528076))

In [19]:
A_values.nbytes / 1e9

0.647904224

In [20]:
A_Centered = A_values - A_values.mean(axis=0)
B_Centered = B_values - B_values.mean(axis=0)

In [21]:
A_Centered

array([[ 0.39725762,  0.33867687, -0.76052614, ..., -1.04539738,
         4.2335739 ,  4.2335739 ],
       [-0.38045267, -0.29267473,  1.87525073, ...,  0.67843199,
        -3.23458995, -3.23458995],
       [-0.19514941,  0.24528712, -1.16237874, ..., -0.81124866,
         2.51998511,  2.51998511],
       ...,
       [ 0.15620159,  0.33084458, -1.63483463, ..., -0.73967025,
        -0.25842133, -0.25842133],
       [-1.15752039, -0.21194606, -1.48396951, ..., -1.30045122,
        -3.82342001, -3.82342001],
       [ 0.3978121 ,  0.022295  , -1.52402896, ..., -1.24756431,
        -0.92551132, -0.92551132]], shape=(53, 1528076))

In [22]:
num = (A_Centered * B_Centered).sum(axis=0)

In [23]:
denom = np.sqrt((A_Centered**2).sum(axis=0) * (B_Centered**2).sum(axis=0))

In [24]:
coexpression = num / denom
coexpression[10:]

/tmp/ipykernel_12888/1158407507.py:1: RuntimeWarning: invalid value encountered in divide
  coexpression = num / denom

array([ 0.52811553,  0.01698002, -0.07952349, ...,  0.15956676,
        0.07064193,  0.31386795], shape=(1528066,))

In [25]:
np.isnan(coexpression).sum()

np.int64(7405)

In [26]:
coexpression = np.nan_to_num(coexpression, nan=0.0)

In [27]:
coexpression.shape

(1528076,)

In [28]:
np.isnan(coexpression).sum()

np.int64(0)

In [29]:
ppi['coexpression'] = coexpression
ppi.head()

        A      B  combined_score  coexpression
0  MAP2K4   FLNC               2      0.285217
1    FNTA  ACVR1               2      0.014917
2   GATA2    PML               2     -0.098040
3    RPA2  STAT3               2      0.350444
4    ARF1   GGA3               2      0.304046

In [ ]:
ppi.to_csv('../data/processed/kidney_PPI_final.csv', index=False)