In [2]:
import pandas as pd
import numpy as np

In [26]:
first_chunk = True

for chunk in pd.read_csv("../data/raw/PPIs/human_annotated_PPIs.txt", sep="\t",chunksize=50000, usecols=["symbol1", "symbol2", "kidney"]):
    colomns_to_keep = chunk[['symbol1','symbol2','kidney']]
    
    filtered = colomns_to_keep[colomns_to_keep['kidney'] >= 1]
    
    if first_chunk:
        filtered.to_csv('../data/processed/Kidney_filter.csv', index=False, mode='w', header=True)
        first_chunk = False
    else:
        filtered.to_csv('../data/processed/Kidney_filter.csv', index=False, mode='a', header=False)

In [3]:
Kidney_filter = pd.read_csv('../data/processed/Kidney_filter.csv')
Kidney_filter.rename(columns={'symbol1':'A','symbol2':'B','kidney':'Combined_score'})

              A        B  Combined_score
0        MAP2K4     FLNC               2
1          FNTA    ACVR1               2
2         GATA2      PML               2
3          RPA2    STAT3               2
4          ARF1     GGA3               2
...         ...      ...             ...
1559854   LAMA2    FBLN2               1
1559855    BMP1     DSPP               1
1559856   SNAI1    LOXL1               1
1559857   FBLN1  COL18A1               2
1559858   FBLN1    LAMA2               2

[1559859 rows x 3 columns]

In [4]:
Kidney_filter.isnull().any()

symbol1    False
symbol2    False
kidney     False
dtype: bool

In [5]:
Kidney_filter[Kidney_filter['symbol1'] == Kidney_filter['symbol2']].sum()

symbol1    MCM2CSRP1KMT2APKD2LMO2RPLP2SNRPACLUFASNS100PSY...
symbol2    MCM2CSRP1KMT2APKD2LMO2RPLP2SNRPACLUFASNS100PSY...
kidney                                                 11096
dtype: object

In [6]:
Kidney_filter = Kidney_filter[Kidney_filter['symbol1'] != Kidney_filter['symbol2']]

In [7]:
Kidney_filter.shape

(1554303, 3)

In [8]:
Kidney_filter.duplicated().sum()

np.int64(1085)

In [9]:
Kidney_filter = Kidney_filter.drop_duplicates()

In [10]:
Kidney_filter.shape

(1553218, 3)

In [11]:
pair = Kidney_filter[['symbol1','symbol2']]
print (pair)

        symbol1  symbol2
0        MAP2K4     FLNC
1          FNTA    ACVR1
2         GATA2      PML
3          RPA2    STAT3
4          ARF1     GGA3
...         ...      ...
1559854   LAMA2    FBLN2
1559855    BMP1     DSPP
1559856   SNAI1    LOXL1
1559857   FBLN1  COL18A1
1559858   FBLN1    LAMA2

[1553218 rows x 2 columns]

In [12]:
from operator import index


pair_filtered = pair.loc[pd.DataFrame(np.sort(pair.values,axis=1),index=pair.index).drop_duplicates().index]
print (pair_filtered)

        symbol1  symbol2
0        MAP2K4     FLNC
1          FNTA    ACVR1
2         GATA2      PML
3          RPA2    STAT3
4          ARF1     GGA3
...         ...      ...
1559854   LAMA2    FBLN2
1559855    BMP1     DSPP
1559856   SNAI1    LOXL1
1559857   FBLN1  COL18A1
1559858   FBLN1    LAMA2

[1547986 rows x 2 columns]

In [13]:
Kidney_filter = Kidney_filter.loc[pair_filtered.index]
Kidney_filter.dtypes

symbol1      str
symbol2      str
kidney     int64
dtype: object

In [14]:
expressions = pd.read_csv('../data/raw/depmap/OmicsExpressionTPMLogp1HumanProteinCodingGenes.csv',nrows=0)

In [15]:
print (expressions)

Empty DataFrame
Columns: [Unnamed: 0, SequencingID, ModelID, IsDefaultEntryForModel, ModelConditionID, IsDefaultEntryForMC, TSPAN6 (7105), TNMD (64102), DPM1 (8813), SCYL3 (57147), FIRRM (55732), FGR (2268), CFH (3075), FUCA2 (2519), GCLC (2729), NFYA (4800), STPG1 (90529), NIPAL3 (57185), LAS1L (81887), ENPP4 (22875), SEMA3F (6405), CFTR (1080), ANKIB1 (54467), CYP51A1 (1595), KRIT1 (889), RAD52 (5893), MYH16 (84176), BAD (572), LAP3 (51056), CD99 (4267), HS3ST1 (9957), AOC1 (26), WNT16 (51384), HECW1 (23072), MAD1L1 (8379), LASP1 (3927), SNX11 (29916), TMEM176A (55365), M6PR (4074), KLHL13 (90293), CYP26B1 (56603), ICA1 (3382), DBNDD1 (79007), ALS2 (57679), CASP10 (843), CFLAR (8837), TFPI (7035), NDUFAF7 (55471), RBM5 (10181), MTMR7 (9108), SLC7A2 (6542), ARF5 (381), SARM1 (23098), POLDIP2 (26073), PLXND1 (23129), AK2 (204), CD38 (952), FKBP4 (2288), KDM1A (23028), RBM6 (10180), CAMKK1 (84254), RECQL (5965), VPS50 (55610), HSPB6 (126393), ARHGAP33 (115703), NDUFAB1 (4706), PDK4 (5166), SLC22A16 (85413), ZMYND10 (51364), ABCB5 (340273), ARX (170302), SLC25A13 (10165), ST7 (7982), CDC27 (996), SLC4A1 (6521), CALCR (799), HCCS (3052), DVL2 (1856), PRSS22 (64063), UPF1 (5976), SKAP2 (8935), SLC25A5 (292), MCUB (55013), HOXA11 (3207), POLR2J (5439), DHX33 (56919), MEOX1 (4222), THSD7A (221981), LIG3 (3980), RPAP3 (79657), ACSM3 (6296), REXO5 (81691), CIAPIN1 (57019), SPPL2B (56928), ATOSB (80256), COPZ2 (51226), PRKAR2B (5577), MSL3 (10943), CREBBP (1387), TSPOAP1 (9256), ...]
Index: []

[0 rows x 19221 columns]

In [16]:
model = pd.read_csv('../data/raw/depmap/Model.csv')
print (model)

         ModelID  PatientID      CellLineName StrippedCellLineName  \
0     ACH-000001  PT-gj46wT       NIH:OVCAR-3            NIHOVCAR3
1     ACH-000002  PT-5qa3uk             HL-60                 HL60
2     ACH-000003  PT-puKIyc             CACO2                CACO2
3     ACH-000004  PT-q4K2cp               HEL                  HEL
4     ACH-000005  PT-q4K2cp        HEL 92.1.7              HEL9217
...          ...        ...               ...                  ...
2127  ACH-003473  PT-fG5tCh  CCLF_PEDS_0013_T        CCLFPEDS0013T
2128  ACH-003474  PT-WxfjG3  CCLF_HNSC_0001_T        CCLFHNSC0001T
2129  ACH-003475  PT-ce6oqw  CCLF_HNSC_0003_T        CCLFHNSC0003T
2130  ACH-003476  PT-ce6oqw  CCLF_HNSC_0002_T        CCLFHNSC0002T
2131  ACH-003480  PT-D6v5Dz  CCLF_THYR_0001_T        CCLFTHYR0001T

     DepmapModelType       OncotreeLineage  \
0              HGSOC  Ovary/Fallopian Tube
1             AMLMRC               Myeloid
2               COAD                 Bowel
3             AMLNOS               Myeloid
4                AML               Myeloid
...              ...                   ...
2127            ERMS           Soft Tissue
2128            HNSC         Head and Neck
2129            HNSC         Head and Neck
2130            ESCC     Esophagus/Stomach
2131            THAP               Thyroid

                     OncotreePrimaryDisease  \
0                  Ovarian Epithelial Tumor
1                    Acute Myeloid Leukemia
2                 Colorectal Adenocarcinoma
3                    Acute Myeloid Leukemia
4                    Acute Myeloid Leukemia
...                                     ...
2127                       Rhabdomyosarcoma
2128  Head and Neck Squamous Cell Carcinoma
2129  Head and Neck Squamous Cell Carcinoma
2130     Esophageal Squamous Cell Carcinoma
2131              Anaplastic Thyroid Cancer

                              OncotreeSubtype OncotreeCode  \
0            High-Grade Serous Ovarian Cancer        HGSOC
1     AML with Myelodysplasia-Related Changes       AMLMRC
2                        Colon Adenocarcinoma         COAD
3                                    AML, NOS       AMLNOS
4                      Acute Myeloid Leukemia          AML
...                                       ...          ...
2127               Embryonal Rhabdomyosarcoma         ERMS
2128    Head and Neck Squamous Cell Carcinoma         HNSC
2129    Head and Neck Squamous Cell Carcinoma         HNSC
2130       Esophageal Squamous Cell Carcinoma         ESCC
2131                Anaplastic Thyroid Cancer         THAP

                                 PatientSubtypeFeatures  ... PublicComments  \
0                                                   NaN  ...            NaN
1     TP53(del), CDKN2A and NRAS mutations [PubMed=2...  ...            NaN
2                                                   NaN  ...            NaN
3                               JAK2 and TP53 mutations  ...            NaN
4                               JAK2 and TP53 mutations  ...            NaN
...                                                 ...  ...            ...
2127                                                NaN  ...            NaN
2128                                                NaN  ...            NaN
2129                                                NaN  ...            NaN
2130                                                NaN  ...            NaN
2131                                                NaN  ...            NaN

                                        CCLEName             HCMIID  \
0                                NIHOVCAR3_OVARY                NaN
1        HL60_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE                NaN
2                          CACO2_LARGE_INTESTINE                NaN
3         HEL_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE                NaN
4     HEL9217_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE                NaN
...                                          ...                ...
2127                                         NaN  HCM-BROD-0006-C49
2128                                         NaN  HCM-BROD-1131-C06
2129                                         NaN                NaN
2130                                         NaN  HCM-BROD-1130-C06
2131                                         NaN                NaN

     PediatricModelType               ModelAvailableInDbgap  \
0                 False  Approved for public sharing - CCLE
1                  True  Approved for public sharing - CCLE
2                 False  Approved for public sharing - CCLE
3                  True  Approved for public sharing - CCLE
4                  True  Approved for public sharing - CCLE
...                 ...                                 ...
2127               True                                 NaN
2128              False                                 NaN
2129              False                                 NaN
2130              False                                 NaN
2131              False                                 NaN

       ModelSubtypeFeatures WTSIMasterCellID SangerModelID  COSMICID  \
0                       NaN           2201.0     SIDM00105  905933.0
1     NRAS, BCOR and CDKN2A             55.0     SIDM00829  905938.0
2                       NaN              NaN     SIDM00891       NaN
3             JAK2 and TP53            783.0     SIDM00594  907053.0
4                       NaN              NaN     SIDM00593       NaN
...                     ...              ...           ...       ...
2127                    NaN              NaN           NaN       NaN
2128                    NaN              NaN           NaN       NaN
2129                    NaN              NaN           NaN       NaN
2130                    NaN              NaN           NaN       NaN
2131                    NaN              NaN           NaN       NaN

     ModelIDAlias
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
...           ...
2127          NaN
2128          NaN
2129          NaN
2130          NaN
2131          NaN

[2132 rows x 49 columns]

In [17]:
gene_cols = expressions.columns[6:]   
gene_cols

Index(['TSPAN6 (7105)', 'TNMD (64102)', 'DPM1 (8813)', 'SCYL3 (57147)',
       'FIRRM (55732)', 'FGR (2268)', 'CFH (3075)', 'FUCA2 (2519)',
       'GCLC (2729)', 'NFYA (4800)',
       ...
       'ATXN8 (724066)', 'SMIM42 (117981789)', 'NPBWR1 (2831)',
       'ACTL10 (170487)', 'RNF228 (122319436)', 'PANO1 (101927423)',
       'HRURF (120766137)', 'PRRC2B (84726)', 'F8A2 (474383)', 'F8A1 (8263)'],
      dtype='str', length=19215)

In [18]:
exprn_genes = expressions.columns[6:].str.split(" (",regex=False).str[0]

In [19]:
(~Kidney_filter["symbol1"].isin(exprn_genes)).sum()

np.int64(10104)

In [20]:
Kidney_filter[~Kidney_filter["symbol1"].isin(exprn_genes)]["symbol1"].nunique()

1039

In [21]:
(~Kidney_filter["symbol2"].isin(exprn_genes)).sum()

np.int64(10014)

In [22]:
Kidney_filter[~Kidney_filter["symbol2"].isin(exprn_genes)]["symbol2"].nunique()

729

In [23]:
kidney_expr_filtered = Kidney_filter[Kidney_filter["symbol1"].isin(exprn_genes) & Kidney_filter["symbol2"].isin(exprn_genes)]

kidney_expr_filtered.shape

(1528076, 3)

In [24]:
pd.concat([kidney_expr_filtered["symbol1"], kidney_expr_filtered["symbol2"]]).nunique()

18359

In [25]:
gene = pd.read_csv("../data/raw/depmap/CRISPRGeneEffect.csv",nrows=0)
gene

Empty DataFrame
Columns: [Unnamed: 0, A1BG (1), A1CF (29974), A2M (2), A2ML1 (144568), A3GALT2 (127550), A4GALT (53947), A4GNT (51146), AAAS (8086), AACS (65985), AADAC (13), AADACL2 (344752), AADACL3 (126767), AADACL4 (343066), AADAT (51166), AAGAB (79719), AAK1 (22848), AAMDC (28971), AAMP (14), AANAT (15), AAR2 (25980), AARD (441376), AARS1 (16), AARS2 (57505), AARSD1 (80755), AASDH (132949), AASDHPPT (60496), AASS (10157), AATF (26574), AATK (9625), ABAT (18), ABCA1 (19), ABCA10 (10349), ABCA12 (26154), ABCA13 (154664), ABCA2 (20), ABCA3 (21), ABCA4 (24), ABCA5 (23461), ABCA6 (23460), ABCA7 (10347), ABCA8 (10351), ABCA9 (10350), ABCB1 (5243), ABCB10 (23456), ABCB11 (8647), ABCB4 (5244), ABCB5 (340273), ABCB6 (10058), ABCB7 (22), ABCB8 (11194), ABCB9 (23457), ABCC1 (4363), ABCC10 (89845), ABCC11 (85320), ABCC12 (94160), ABCC2 (1244), ABCC3 (8714), ABCC4 (10257), ABCC5 (10057), ABCC6 (368), ABCC8 (6833), ABCC9 (10060), ABCD1 (215), ABCD2 (225), ABCD3 (5825), ABCD4 (5826), ABCE1 (6059), ABCF1 (23), ABCF3 (55324), ABCG1 (9619), ABCG2 (9429), ABCG4 (64137), ABCG5 (64240), ABCG8 (64241), ABHD1 (84696), ABHD10 (55347), ABHD11 (83451), ABHD12 (26090), ABHD12B (145447), ABHD13 (84945), ABHD14A (25864), ABHD14B (84836), ABHD15 (116236), ABHD16A (7920), ABHD16B (140701), ABHD17A (81926), ABHD17B (51104), ABHD17C (58489), ABHD18 (80167), ABHD2 (11057), ABHD3 (171586), ABHD4 (63874), ABHD5 (51099), ABHD6 (57406), ABHD8 (79575), ABI1 (10006), ABI2 (10152), ABI3 (51225), ABI3BP (25890), ...]
Index: []

[0 rows x 18436 columns]

In [26]:
gene_lab = gene.columns[1:].str.split(" (",regex=False).str[0]
gene_lab

Index(['A1BG', 'A1CF', 'A2M', 'A2ML1', 'A3GALT2', 'A4GALT', 'A4GNT', 'AAAS',
       'AACS', 'AADAC',
       ...
       'ZWILCH', 'ZWINT', 'ZXDA', 'ZXDB', 'ZXDC', 'ZYG11A', 'ZYG11B', 'ZYX',
       'ZZEF1', 'ZZZ3'],
      dtype='str', length=18435)

In [27]:
ppi_genes = pd.concat([kidney_expr_filtered["symbol1"], kidney_expr_filtered["symbol2"]]).unique()

sum(pd.Series(ppi_genes).isin(gene_lab))

17863

In [28]:
kidney_expr_filtered.rename(columns={'symbol1':'A','symbol2':'B','kidney':'combined_score'})

              A        B  combined_score
0        MAP2K4     FLNC               2
1          FNTA    ACVR1               2
2         GATA2      PML               2
3          RPA2    STAT3               2
4          ARF1     GGA3               2
...         ...      ...             ...
1559854   LAMA2    FBLN2               1
1559855    BMP1     DSPP               1
1559856   SNAI1    LOXL1               1
1559857   FBLN1  COL18A1               2
1559858   FBLN1    LAMA2               2

[1528076 rows x 3 columns]

In [30]:
for i in range(0,len(kidney_expr_filtered),100000):
    chunk = kidney_expr_filtered.iloc[i:i+100000]
    if i == 0:
        chunk.to_csv('../data/processed/kidney_PPI_final.csv',index=False,mode='w')
    else:
        chunk.to_csv('../data/processed/kidney_PPI_final.csv',index=False,mode='a',header=False)

In [36]:
PPI_kidney = pd.read_csv('../data/processed/kidney_PPI_final.csv')

PPI_kidney.rename(columns={'symbol1':'A','symbol2':'B','kidney':'combined_score'}).to_csv('../data/processed/kidney_PPI_final.csv', index=False)